### ISSUE TITLE
How the cls_upscaling helps to predict masks with categories?

### ISSUE THREAD

**Issue by zkjisj** [xypu98/CWSAM#15]
In the code, the add of cls_upsacling produces the cls_upscaled_embedding with shape b * (c * num_classes // 8) * h * w. The shape of hyper_in is b * 4 * (c//8)， why hyper_in @ cls_upscaled_embedding can be executed?
![image](https://github.com/xypu98/CWSAM/assets/88485154/6cf46fb1-2a58-49c6-91ae-0c194a558682)
If it can be executed, this will produce masks with shape b * (c // 8 ) * ( num_classes * h * w ), it then be view as b * num_mask_tokens (5?)  * -1 * h * w， how it happens without num_classes? I'm still confused about why the final masks will with categories, that I mean the function of num_classes.
![image](https://github.com/xypu98/CWSAM/assets/88485154/80a1360b-f4d8-434b-a640-9a50ad63e45e)

**Comment by xypu98** [comment]
we only output one mask, keep the channel dimension of output mask same to the number of classes and calculate the loss between the corresponding categories. It works.

**Comment by zkjisj** [comment]
Thanks a lot for your explanation！I really appreciate your help, and I understand the concept much better.
