### ISSUE TITLE
数据划分问题

### ISSUE THREAD

**Issue by DBook111** [xypu98/CWSAM#8]
很荣幸能读到您的工作，
您在论文中划分FUSAR数据集中武汉的80个切片作为测试集，但是我在你们中下载的数据集(包含四个类别)的武汉有170张切片（从213-382），请问这是什么情况呢？

**Comment by xypu98** [comment]
> 很荣幸能读到您的工作， 您在论文中划分FUSAR数据集中武汉的80个切片作为测试集，但是我在你们中下载的数据集(包含四个类别)的武汉有170张切片（从213-382），请问这是什么情况呢？

303-382为测试集，和FUSAR-MAP1.0数据集发布的那篇jstars论文实验测试集保持一致

**Comment by DBook111** [comment]
好的，谢谢！！！
